### ISSUE TITLE
Paper request

### ISSUE THREAD

**Issue by caigentan** [yikaiw/CEN#1]
Hello, I am interested in your research. I want to get a deeper understanding by reading your paper, but I could not retrieve your paper on arxiv.org. Can you give me this paper? ? I promise that it will only be used for personal research and not spread, my email address is: billtan884.8@gmail.com, thank you very much

**Comment by yikaiw** [comment]
Thanks for your interest in our work. We are improving our paper, and will make the paper available in the following 1~2 days.

**Comment by caigentan** [comment]
> Thanks for your interest in our work. We are improving our paper, and will make the paper available in the following 1~2 days.

Ok, thank you very much for your reply

**Comment by yikaiw** [comment]
The paper is now available at: https://yikaiw.github.io/projects/NeurIPS20-CEN/paper.pdf
