### ISSUE TITLE
为什么对rgb, depth和ens的loss求和？

### ISSUE THREAD

**Issue by ZqCATCAT** [yikaiw/CEN#15]
作者你好！在文章的loss公式中，我的理解是只将ens拿来算loss。为什么代码里面需要对rgb，depth和ens的loss求和。

**Comment by yikaiw** [comment]
代码中分别对rgb，depth和ens的loss求和，主要为了解耦ens weight和网络的学习过程，即在更新ens weight时网络参数不更新。

https://github.com/yikaiw/CEN/blob/40f277ed1a377a3c81f979a6c534ae268773aa9d/semantic_segmentation/models/model.py#L316
