### ISSUE TITLE
About visualization figures in paper

### ISSUE THREAD

**Issue by Sibyl233** [yikaiw/CEN#2]
![image](https://user-images.githubusercontent.com/24403298/103270403-c91d8380-49f2-11eb-8062-5a1d9f4042c8.png)
Hi, thanks for your job. I wonder what 'averaged' means in Figure3, since the visualized feature maps are chosen by scaling factor in BN layer. And may I ask which layer/stage are these feature maps belonged to specifically？Because I really want to know whether the outdoor datasets have such characters.  I'd be grateful if you would describe it in more detail.

**Comment by yikaiw** [comment]
In this work, feature maps for each layer can be categorized into three kinds: gamma_rgb>0, gamma_depth=0; gamma_rgb=0, gamma_depth>0; both>0. There won't be both=0 as we apply sparsity constraints on disjoint channels. 

'averaged' means: 1. extracting feature maps at specific channels (e.g. channels with gamma_rgb>0, gamma_depth=0); 2. average these feature maps along the channels. 

For plotting Figure 3, we use the 9th layer of ResNet, i.e. the 2nd layer of the 3rd stage (with 256 channels) of ResNet.

**Comment by Sibyl233** [comment]
Thanks a lot for your reply 👍

**Comment by cjs123456** [comment]
Thanks for your great job, but may I ask what the numbers in the legend (e.g. 0.0025, 0.0075) means? ![image](https://user-images.githubusercontent.com/52772958/184884287-1f0ebc1c-4ab3-465f-90fd-96190b8e0e9c.png) It seems like they should be the values of scaling factors, but in the figure they should be the average of the chosen feature maps? In addition, did you add any filters to the average of the feature maps? They look very smooth.

**Comment by yikaiw** [comment]
They are the average of the chosen feature maps (after BN), and thus the values of scaling factors are counted in. We do not apply filters on the averaged feature maps.

**Comment by yikaiw** [comment]
> Thanks for your great job, but may I ask what the numbers in the legend (e.g. 0.0025, 0.0075) means? ![image](https://user-images.githubusercontent.com/52772958/184884287-1f0ebc1c-4ab3-465f-90fd-96190b8e0e9c.png) It seems like they should be the values of scaling factors, but in the figure they should be the average of the chosen feature maps? In addition, did you add any filters to the average of the feature maps? They look very smooth.

@cjs123456 They are the average of the chosen feature maps (after BN), and thus the values of scaling factors have been counted in. We do not apply filters on the averaged feature maps.

**Comment by cjs123456** [comment]
> > Thanks for your great job, but may I ask what the numbers in the legend (e.g. 0.0025, 0.0075) means? ![image](https://user-images.githubusercontent.com/52772958/184884287-1f0ebc1c-4ab3-465f-90fd-96190b8e0e9c.png) It seems like they should be the values of scaling factors, but in the figure they should be the average of the chosen feature maps? In addition, did you add any filters to the average of the feature maps? They look very smooth.
> 
> @cjs123456 They are the average of the chosen feature maps (after BN), and thus the values of scaling factors have been counted in. We do not apply filters on the averaged feature maps.

Thanks a lot for your reply. I know they are the average of the chosen feature maps，but what does the colorbar mean？A redder color in the figure means a higher scaling factor？or just a higher value of the averaged feature maps?

**Comment by yikaiw** [comment]
@cjs123456 A redder color means a higher value of the averaged feature maps.

**Comment by cjs123456** [comment]
OK, thanks for your reply！
