### ISSUE TITLE
About where the mean(ensemble) is calculated

### ISSUE THREAD

**Issue by slyviacassell** [yikaiw/CEN#3]
Hi, I find that the function `validate()` in the segmentation experiment may be wrong. It looks like [this](https://github.com/yikaiw/CEN/blob/9acd24f827e011b134d989e557790ac051577100/semantic_segmentation/main.py#L346-L359). The annotation says
```python
    """Validate segmenter
    Args:
      segmenter (nn.Module) : segmentation network
      val_loader (DataLoader) : training data iterator
      epoch (int) : current epoch
      num_classes (int) : number of classes to consider
    Returns:
      Mean IoU (float)
    """
```
, but I do not find any operation to calculate the mean value of `IoU` between the output of `RGB` and that of `depth`. It seems just return the `IoU` of `depth`, not the mean value. Would you mind giving more details of this?

**Comment by yikaiw** [comment]
Hi, as you say "the mean value of IoU between the output of RGB and that of depth", does the "mean value" indicates the `ensemble `of RGB and Depth? If it does, in Line 346 of main.py, `for idx, input_type in enumerate(input_types + ['ens']):`, there is an ensemble term appended to `input_types `. Therefore the returned `IoU` should be evaluated on the `ensemble`, not the `depth `. Any questions are welcome.

**Comment by yikaiw** [comment]
@slyviacassell Hi, as you say "the mean value of IoU between the output of RGB and that of depth", does the "mean value" indicates the `ensemble` of RGB and Depth? If it does, in Line 346 of main.py, `for idx, input_type in  #enumerate(input_types + ['ens']):`, there is an ensemble term appended to `input_types`. Therefore the returned `IoU` should be evaluated on `ensemble`, not `depth`. 

Besides, note that the network returns a list with three tensors, which are the outputs of the RGB, Depth and Ensemble respectively. The calculation of the ensemble is performed at Line 313-316 in models/model.py. You can have a look at my training logs, shared in the Google Drive. In the training logs, each validation step prints three lines of results, including results on RGB, Depth and **Ensemble** respectively as well.

Questions are welcome.

**Comment by slyviacassell** [comment]
Whoops, my fault. I just misunderstand it. Thank you for your prompt reply!

**Comment by slyviacassell** [comment]
@yikaiw Hi, I found that the ensembled output is [detached](https://github.com/yikaiw/CEN/blob/9acd24f827e011b134d989e557790ac051577100/semantic_segmentation/models/model.py#L316) from the computing graph in the segmentation experiment, which means the ensemble output would not be used to [backforward](https://github.com/yikaiw/CEN/blob/9acd24f827e011b134d989e557790ac051577100/semantic_segmentation/main.py#L276-L283).  Would you mind providing some details?

**Comment by yikaiw** [comment]
Yes, as network parameters have already been updated through RGB and depth branches, the ensemble output is only for updating alpha (ensemble weights), which does not affect the network learning.

**Comment by slyviacassell** [comment]
Ok, thank you very much!
