### ISSUE TITLE
最终表示的问题

### ISSUE THREAD

**Issue by bourne-3** [yikaiw/CEN#5]
你们的工作做得非常的棒。我想问一下：经过CEN的fusion之后，如果我要进行多模态情感分析（有三个模态：文本，音频以及视频），从文章看说经过fusion之后仍然是三个输出，每个输出都有了其他模态的信息了。现在我要进行情感预测，我是只取其中的一个模态进预测还是把他们给拼接起来呢？

**Comment by yikaiw** [comment]
Thank you for your appreciation. Currently, our method is only verified on homogeneous modalities like RGB and depth, yet is not verified on tasks containing images and texts. In our method, we adopt a learnable ensemble over the final predictions, which is empirically better than concatenating the final predictions.

**Comment by yikaiw** [comment]
Thank you for your appreciation. Currently, our method is only verified on homogeneous modalities such as RGB, depth, normal, etc, yet is not verified on tasks containing images and texts. In our method, we adopt a learnable ensemble over the final predictions, which is empirically better than concatenating the final predictions.

**Comment by bourne-3** [comment]
Ok，thanks for your reminding.I intend to use the CEN on Heterogeneous data and verify the performance of it.May I ask what the specific learnable ensemble is?Is it use each modality to make predictions and then vote?

**Comment by yikaiw** [comment]
The ensemble is a weighted sum of predictions, performed at Line 313-316 in models/model.py for semantic segmentation, and the weights for the ensemble are obtained by optimization.

**Comment by bourne-3** [comment]
Got it，thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yikaiw/CEN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月28日(星期天) 中午11:05
收件人:&nbsp;"yikaiw/CEN"<CEN@noreply.github.com&gt;;
抄送:&nbsp;"李泽彬"<595962708@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yikaiw/CEN] 最终表示的问题 (#5)





 
The ensemble is a weighted sum of predictions, performed at Line 313-316 in models/model.py for semantic segmentation, and the weights for the ensemble are obtained by optimization.
