### ISSUE TITLE
some question for image size

### ISSUE THREAD

**Issue by jianyulei1** [yikaiw/CEN#7]
Thanks for your excellent work！I want to input images with different height and width, but I will get an error.Do the images input have to be the same height and width?
Thank you very much and look forward your reply.

**Comment by yikaiw** [comment]
Hi, thanks for your interest. You can change the height and width as long as you adjust SHORTER_SIDE and CROP_SIZE in the config.py file. Could you provide the error so that I can further check it?

**Comment by jianyulei1** [comment]
Thank you for your reply, I use image2image_translation, but the default input is 256 * 256. I want to input a 640 * 480 image, how do I adjust the code?

**Comment by yikaiw** [comment]
For image2image_translation, it may be not easy to change the size, since the generated images may be confused. There are works that deal with high-resolution image2image translation.

**Comment by jianyulei1** [comment]
您好，您之前给我回复说有处理高分辨的image2image的代码，您能提供给我吗，我对这个很感兴趣想学习一下，非常感谢您的回复。



---Original---
From: "Yikai ***@***.***&gt;
Date: Wed, Jun 2, 2021 00:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yikaiw/CEN] some question for image size (#7)




 
For image2image_translation, it may be not easy to change the size, since the generated images may be confused. There are works that deal with high-resolution image2image translation.

**Comment by yikaiw** [comment]
A typical work for high-resolution image2image translation is **https://github.com/NVIDIA/pix2pixHD**, though it is not multimodal-supported.

**Comment by jianyulei1** [comment]
非常感谢您的回复，祝您工作顺利。



---Original---
From: "Yikai ***@***.***&gt;
Date: Wed, Jun 2, 2021 00:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yikaiw/CEN] some question for image size (#7)




 
A typical work for high-resolution image2image translation is https://github.com/NVIDIA/pix2pixHD, though it is not multimodal-supported.
